# Generated by Django 3.2.6 on 2021-09-10 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Details',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('college_name', models.CharField(max_length=50)),
                ('student_year', models.CharField(max_length=20)),
                ('branch_name', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('hometown', models.CharField(max_length=20)),
                ('test_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Test',
            fields=[
                ('pt_id', models.AutoField(primary_key=True, serialize=False)),
                ('initiative', models.IntegerField(default='', null=True)),
                ('sees_act', models.IntegerField(default='', null=True)),
                ('persistence', models.IntegerField(default='', null=True)),
                ('info_seek', models.IntegerField(default='', null=True)),
                ('concern_high', models.IntegerField(default='', null=True)),
                ('commitment_work', models.IntegerField(default='', null=True)),
                ('efficiency_orientation', models.IntegerField(default='', null=True)),
                ('systematic_planning', models.IntegerField(default='', null=True)),
                ('problem_solving', models.IntegerField(default='', null=True)),
                ('self_confidence', models.IntegerField(default='', null=True)),
                ('assertiveness', models.IntegerField(default='', null=True)),
                ('persuasion', models.IntegerField(default='', null=True)),
                ('use_of_influence', models.IntegerField(default='', null=True)),
                ('average_competency', models.FloatField(default='', null=True)),
                ('correction_factor', models.IntegerField(default='', null=True)),
                ('student_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student.student_details')),
            ],
        ),
        migrations.CreateModel(
            name='Meta_Cognitive_Test',
            fields=[
                ('mct_id', models.AutoField(primary_key=True, serialize=False)),
                ('planning_skill', models.IntegerField(default='', null=True)),
                ('implementation_skill', models.IntegerField(default='', null=True)),
                ('monitoring_skill', models.IntegerField(default='', null=True)),
                ('evalauation_skill', models.IntegerField(default='', null=True)),
                ('student_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student.student_details')),
            ],
        ),
        migrations.CreateModel(
            name='Intellectual_Capacity',
            fields=[
                ('ic_id', models.AutoField(primary_key=True, serialize=False)),
                ('clear_thinking', models.IntegerField(default='', null=True)),
                ('observational_ability', models.IntegerField(default='', null=True)),
                ('reasoning_ability', models.IntegerField(default='', null=True)),
                ('critical_reasoning', models.IntegerField(default='', null=True)),
                ('abstract_reasoning', models.IntegerField(default='', null=True)),
                ('intelligence_quotient', models.IntegerField(default='', null=True)),
                ('student_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student.student_details')),
            ],
        ),
        migrations.CreateModel(
            name='Emotional_Intelligence',
            fields=[
                ('ei_id', models.AutoField(primary_key=True, serialize=False)),
                ('self_awareness', models.FloatField(default='', null=True)),
                ('self_management', models.FloatField(default='', null=True)),
                ('social_awareness', models.FloatField(default='', null=True)),
                ('social_skills', models.FloatField(default='', null=True)),
                ('emotional_intelligence', models.FloatField(default='', null=True)),
                ('emotional_quotient', models.FloatField(default='', null=True)),
                ('student', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='student.student_details')),
            ],
        ),
    ]
